/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2ContactEdge : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ContactEdge(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2ContactEdge obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ContactEdge() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ContactEdge(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Body other {
    set {
      Box2DPINVOKE.b2ContactEdge_other_set(swigCPtr, b2Body.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ContactEdge_other_get(swigCPtr);
      b2Body ret = (cPtr == IntPtr.Zero) ? null : new b2Body(cPtr, false);
      return ret;
    } 
  }

  public b2Contact contact {
    set {
      Box2DPINVOKE.b2ContactEdge_contact_set(swigCPtr, b2Contact.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ContactEdge_contact_get(swigCPtr);
      b2Contact ret = (cPtr == IntPtr.Zero) ? null : new b2Contact(cPtr, false);
      return ret;
    } 
  }

  public b2ContactEdge prev {
    set {
      Box2DPINVOKE.b2ContactEdge_prev_set(swigCPtr, b2ContactEdge.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ContactEdge_prev_get(swigCPtr);
      b2ContactEdge ret = (cPtr == IntPtr.Zero) ? null : new b2ContactEdge(cPtr, false);
      return ret;
    } 
  }

  public b2ContactEdge next {
    set {
      Box2DPINVOKE.b2ContactEdge_next_set(swigCPtr, b2ContactEdge.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ContactEdge_next_get(swigCPtr);
      b2ContactEdge ret = (cPtr == IntPtr.Zero) ? null : new b2ContactEdge(cPtr, false);
      return ret;
    } 
  }

  public b2ContactEdge() : this(Box2DPINVOKE.new_b2ContactEdge(), true) {
  }

}

}
