/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2ContactID : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ContactID(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2ContactID obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ContactID() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ContactID(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2ContactFeature cf {
    set {
      Box2DPINVOKE.b2ContactID_cf_set(swigCPtr, b2ContactFeature.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ContactID_cf_get(swigCPtr);
      b2ContactFeature ret = (cPtr == IntPtr.Zero) ? null : new b2ContactFeature(cPtr, false);
      return ret;
    } 
  }

  public uint key {
    set {
      Box2DPINVOKE.b2ContactID_key_set(swigCPtr, value);
    } 
    get {
      uint ret = Box2DPINVOKE.b2ContactID_key_get(swigCPtr);
      return ret;
    } 
  }

  public b2ContactID() : this(Box2DPINVOKE.new_b2ContactID(), true) {
  }

}

}
