/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2DynamicTree : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2DynamicTree(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2DynamicTree obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2DynamicTree() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2DynamicTree(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2DynamicTree() : this(Box2DPINVOKE.new_b2DynamicTree(), true) {
  }

  public int CreateProxy(b2AABB aabb, SWIGTYPE_p_void userData) {
    int ret = Box2DPINVOKE.b2DynamicTree_CreateProxy(swigCPtr, b2AABB.getCPtr(aabb), SWIGTYPE_p_void.getCPtr(userData));
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void DestroyProxy(int proxyId) {
    Box2DPINVOKE.b2DynamicTree_DestroyProxy(swigCPtr, proxyId);
  }

  public bool MoveProxy(int proxyId, b2AABB aabb1, b2Vec2 displacement) {
    bool ret = Box2DPINVOKE.b2DynamicTree_MoveProxy(swigCPtr, proxyId, b2AABB.getCPtr(aabb1), b2Vec2.getCPtr(displacement));
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_void GetUserData(int proxyId) {
    IntPtr cPtr = Box2DPINVOKE.b2DynamicTree_GetUserData(swigCPtr, proxyId);
    SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public b2AABB GetFatAABB(int proxyId) {
    b2AABB ret = new b2AABB(Box2DPINVOKE.b2DynamicTree_GetFatAABB(swigCPtr, proxyId), false);
    return ret;
  }

  public void Validate() {
    Box2DPINVOKE.b2DynamicTree_Validate(swigCPtr);
  }

  public int GetHeight() {
    int ret = Box2DPINVOKE.b2DynamicTree_GetHeight(swigCPtr);
    return ret;
  }

  public int GetMaxBalance() {
    int ret = Box2DPINVOKE.b2DynamicTree_GetMaxBalance(swigCPtr);
    return ret;
  }

  public float GetAreaRatio() {
    float ret = Box2DPINVOKE.b2DynamicTree_GetAreaRatio(swigCPtr);
    return ret;
  }

  public void RebuildBottomUp() {
    Box2DPINVOKE.b2DynamicTree_RebuildBottomUp(swigCPtr);
  }

}

}
