/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2GearJointDef : b2JointDef {
  private HandleRef swigCPtr;

  internal b2GearJointDef(IntPtr cPtr, bool cMemoryOwn) : base(Box2DPINVOKE.b2GearJointDef_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2GearJointDef obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2GearJointDef() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2GearJointDef(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public b2GearJointDef() : this(Box2DPINVOKE.new_b2GearJointDef(), true) {
  }

  public b2Joint joint1 {
    set {
      Box2DPINVOKE.b2GearJointDef_joint1_set(swigCPtr, b2Joint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2GearJointDef_joint1_get(swigCPtr);
      b2Joint ret = (cPtr == IntPtr.Zero) ? null : new b2Joint(cPtr, false);
      return ret;
    } 
  }

  public b2Joint joint2 {
    set {
      Box2DPINVOKE.b2GearJointDef_joint2_set(swigCPtr, b2Joint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2GearJointDef_joint2_get(swigCPtr);
      b2Joint ret = (cPtr == IntPtr.Zero) ? null : new b2Joint(cPtr, false);
      return ret;
    } 
  }

  public float ratio {
    set {
      Box2DPINVOKE.b2GearJointDef_ratio_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2GearJointDef_ratio_get(swigCPtr);
      return ret;
    } 
  }

}

}
