/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2JointDef : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2JointDef(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2JointDef obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2JointDef() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2JointDef(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2JointDef() : this(Box2DPINVOKE.new_b2JointDef(), true) {
  }

  public b2JointType type {
    set {
      Box2DPINVOKE.b2JointDef_type_set(swigCPtr, (int)value);
    } 
    get {
      b2JointType ret = (b2JointType)Box2DPINVOKE.b2JointDef_type_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void userData {
    set {
      Box2DPINVOKE.b2JointDef_userData_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2JointDef_userData_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public b2Body bodyA {
    set {
      Box2DPINVOKE.b2JointDef_bodyA_set(swigCPtr, b2Body.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2JointDef_bodyA_get(swigCPtr);
      b2Body ret = (cPtr == IntPtr.Zero) ? null : new b2Body(cPtr, false);
      return ret;
    } 
  }

  public b2Body bodyB {
    set {
      Box2DPINVOKE.b2JointDef_bodyB_set(swigCPtr, b2Body.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2JointDef_bodyB_get(swigCPtr);
      b2Body ret = (cPtr == IntPtr.Zero) ? null : new b2Body(cPtr, false);
      return ret;
    } 
  }

  public bool collideConnected {
    set {
      Box2DPINVOKE.b2JointDef_collideConnected_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2JointDef_collideConnected_get(swigCPtr);
      return ret;
    } 
  }

}

}
