/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2MassData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2MassData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2MassData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2MassData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2MassData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public float mass {
    set {
      Box2DPINVOKE.b2MassData_mass_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2MassData_mass_get(swigCPtr);
      return ret;
    } 
  }

  public b2Vec2 center {
    set {
      Box2DPINVOKE.b2MassData_center_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2MassData_center_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public float I {
    set {
      Box2DPINVOKE.b2MassData_I_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2MassData_I_get(swigCPtr);
      return ret;
    } 
  }

  public b2MassData() : this(Box2DPINVOKE.new_b2MassData(), true) {
  }

}

}
