/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2Manifold : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Manifold(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2Manifold obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Manifold() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Manifold(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2ManifoldPoint points {
    set {
      Box2DPINVOKE.b2Manifold_points_set(swigCPtr, b2ManifoldPoint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2Manifold_points_get(swigCPtr);
      b2ManifoldPoint ret = (cPtr == IntPtr.Zero) ? null : new b2ManifoldPoint(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localNormal {
    set {
      Box2DPINVOKE.b2Manifold_localNormal_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2Manifold_localNormal_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localPoint {
    set {
      Box2DPINVOKE.b2Manifold_localPoint_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2Manifold_localPoint_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Manifold.Type type {
    set {
      Box2DPINVOKE.b2Manifold_type_set(swigCPtr, (int)value);
    } 
    get {
      b2Manifold.Type ret = (b2Manifold.Type)Box2DPINVOKE.b2Manifold_type_get(swigCPtr);
      return ret;
    } 
  }

  public int pointCount {
    set {
      Box2DPINVOKE.b2Manifold_pointCount_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2Manifold_pointCount_get(swigCPtr);
      return ret;
    } 
  }

  public b2Manifold() : this(Box2DPINVOKE.new_b2Manifold(), true) {
  }

  public enum Type {
    e_circles,
    e_faceA,
    e_faceB
  }

}

}
