/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2PrismaticJointDef : b2JointDef {
  private HandleRef swigCPtr;

  internal b2PrismaticJointDef(IntPtr cPtr, bool cMemoryOwn) : base(Box2DPINVOKE.b2PrismaticJointDef_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2PrismaticJointDef obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2PrismaticJointDef() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2PrismaticJointDef(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public b2PrismaticJointDef() : this(Box2DPINVOKE.new_b2PrismaticJointDef(), true) {
  }

  public void Initialize(b2Body bodyA, b2Body bodyB, b2Vec2 anchor, b2Vec2 axis) {
    Box2DPINVOKE.b2PrismaticJointDef_Initialize(swigCPtr, b2Body.getCPtr(bodyA), b2Body.getCPtr(bodyB), b2Vec2.getCPtr(anchor), b2Vec2.getCPtr(axis));
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public b2Vec2 localAnchorA {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_localAnchorA_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2PrismaticJointDef_localAnchorA_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localAnchorB {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_localAnchorB_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2PrismaticJointDef_localAnchorB_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localAxisA {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_localAxisA_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2PrismaticJointDef_localAxisA_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public float referenceAngle {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_referenceAngle_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PrismaticJointDef_referenceAngle_get(swigCPtr);
      return ret;
    } 
  }

  public bool enableLimit {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_enableLimit_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2PrismaticJointDef_enableLimit_get(swigCPtr);
      return ret;
    } 
  }

  public float lowerTranslation {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_lowerTranslation_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PrismaticJointDef_lowerTranslation_get(swigCPtr);
      return ret;
    } 
  }

  public float upperTranslation {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_upperTranslation_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PrismaticJointDef_upperTranslation_get(swigCPtr);
      return ret;
    } 
  }

  public bool enableMotor {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_enableMotor_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2PrismaticJointDef_enableMotor_get(swigCPtr);
      return ret;
    } 
  }

  public float maxMotorForce {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_maxMotorForce_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PrismaticJointDef_maxMotorForce_get(swigCPtr);
      return ret;
    } 
  }

  public float motorSpeed {
    set {
      Box2DPINVOKE.b2PrismaticJointDef_motorSpeed_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PrismaticJointDef_motorSpeed_get(swigCPtr);
      return ret;
    } 
  }

}

}
