/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2Rot : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Rot(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2Rot obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Rot() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Rot(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Rot() : this(Box2DPINVOKE.new_b2Rot__SWIG_0(), true) {
  }

  public b2Rot(float angle) : this(Box2DPINVOKE.new_b2Rot__SWIG_1(angle), true) {
  }

  public void Set(float angle) {
    Box2DPINVOKE.b2Rot_Set(swigCPtr, angle);
  }

  public void SetIdentity() {
    Box2DPINVOKE.b2Rot_SetIdentity(swigCPtr);
  }

  public float GetAngle() {
    float ret = Box2DPINVOKE.b2Rot_GetAngle(swigCPtr);
    return ret;
  }

  public b2Vec2 GetXAxis() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2Rot_GetXAxis(swigCPtr), true);
    return ret;
  }

  public b2Vec2 GetYAxis() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2Rot_GetYAxis(swigCPtr), true);
    return ret;
  }

  public float s {
    set {
      Box2DPINVOKE.b2Rot_s_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Rot_s_get(swigCPtr);
      return ret;
    } 
  }

  public float c {
    set {
      Box2DPINVOKE.b2Rot_c_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Rot_c_get(swigCPtr);
      return ret;
    } 
  }

}

}
