/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2SimplexCache : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2SimplexCache(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2SimplexCache obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2SimplexCache() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2SimplexCache(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public float metric {
    set {
      Box2DPINVOKE.b2SimplexCache_metric_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2SimplexCache_metric_get(swigCPtr);
      return ret;
    } 
  }

  public ushort count {
    set {
      Box2DPINVOKE.b2SimplexCache_count_set(swigCPtr, value);
    } 
    get {
      ushort ret = Box2DPINVOKE.b2SimplexCache_count_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char indexA {
    set {
      Box2DPINVOKE.b2SimplexCache_indexA_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2SimplexCache_indexA_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char indexB {
    set {
      Box2DPINVOKE.b2SimplexCache_indexB_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2SimplexCache_indexB_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public b2SimplexCache() : this(Box2DPINVOKE.new_b2SimplexCache(), true) {
  }

}

}
