/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2TimeStep : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2TimeStep(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2TimeStep obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2TimeStep() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2TimeStep(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public float dt {
    set {
      Box2DPINVOKE.b2TimeStep_dt_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2TimeStep_dt_get(swigCPtr);
      return ret;
    } 
  }

  public float inv_dt {
    set {
      Box2DPINVOKE.b2TimeStep_inv_dt_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2TimeStep_inv_dt_get(swigCPtr);
      return ret;
    } 
  }

  public float dtRatio {
    set {
      Box2DPINVOKE.b2TimeStep_dtRatio_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2TimeStep_dtRatio_get(swigCPtr);
      return ret;
    } 
  }

  public int velocityIterations {
    set {
      Box2DPINVOKE.b2TimeStep_velocityIterations_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2TimeStep_velocityIterations_get(swigCPtr);
      return ret;
    } 
  }

  public int positionIterations {
    set {
      Box2DPINVOKE.b2TimeStep_positionIterations_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2TimeStep_positionIterations_get(swigCPtr);
      return ret;
    } 
  }

  public bool warmStarting {
    set {
      Box2DPINVOKE.b2TimeStep_warmStarting_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2TimeStep_warmStarting_get(swigCPtr);
      return ret;
    } 
  }

  public b2TimeStep() : this(Box2DPINVOKE.new_b2TimeStep(), true) {
  }

}

}
