/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2Vec3 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Vec3(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2Vec3 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Vec3() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Vec3(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Vec3() : this(Box2DPINVOKE.new_b2Vec3__SWIG_0(), true) {
  }

  public b2Vec3(float x, float y, float z) : this(Box2DPINVOKE.new_b2Vec3__SWIG_1(x, y, z), true) {
  }

  public void SetZero() {
    Box2DPINVOKE.b2Vec3_SetZero(swigCPtr);
  }

  public void Set(float x_, float y_, float z_) {
    Box2DPINVOKE.b2Vec3_Set(swigCPtr, x_, y_, z_);
  }

  public float x {
    set {
      Box2DPINVOKE.b2Vec3_x_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec3_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      Box2DPINVOKE.b2Vec3_y_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec3_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      Box2DPINVOKE.b2Vec3_z_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec3_z_get(swigCPtr);
      return ret;
    } 
  }

}

}
