/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2WheelJointDef : b2JointDef {
  private HandleRef swigCPtr;

  internal b2WheelJointDef(IntPtr cPtr, bool cMemoryOwn) : base(Box2DPINVOKE.b2WheelJointDef_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2WheelJointDef obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2WheelJointDef() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2WheelJointDef(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public b2WheelJointDef() : this(Box2DPINVOKE.new_b2WheelJointDef(), true) {
  }

  public void Initialize(b2Body bodyA, b2Body bodyB, b2Vec2 anchor, b2Vec2 axis) {
    Box2DPINVOKE.b2WheelJointDef_Initialize(swigCPtr, b2Body.getCPtr(bodyA), b2Body.getCPtr(bodyB), b2Vec2.getCPtr(anchor), b2Vec2.getCPtr(axis));
    
  }

  public b2Vec2 localAnchorA {
    set {
      Box2DPINVOKE.b2WheelJointDef_localAnchorA_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2WheelJointDef_localAnchorA_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localAnchorB {
    set {
      Box2DPINVOKE.b2WheelJointDef_localAnchorB_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2WheelJointDef_localAnchorB_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localAxisA {
    set {
      Box2DPINVOKE.b2WheelJointDef_localAxisA_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2WheelJointDef_localAxisA_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public bool enableMotor {
    set {
      Box2DPINVOKE.b2WheelJointDef_enableMotor_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2WheelJointDef_enableMotor_get(swigCPtr);
      return ret;
    } 
  }

  public float maxMotorTorque {
    set {
      Box2DPINVOKE.b2WheelJointDef_maxMotorTorque_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2WheelJointDef_maxMotorTorque_get(swigCPtr);
      return ret;
    } 
  }

  public float motorSpeed {
    set {
      Box2DPINVOKE.b2WheelJointDef_motorSpeed_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2WheelJointDef_motorSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public float frequencyHz {
    set {
      Box2DPINVOKE.b2WheelJointDef_frequencyHz_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2WheelJointDef_frequencyHz_get(swigCPtr);
      return ret;
    } 
  }

  public float dampingRatio {
    set {
      Box2DPINVOKE.b2WheelJointDef_dampingRatio_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2WheelJointDef_dampingRatio_get(swigCPtr);
      return ret;
    } 
  }

}

}
