/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2ClipVertex : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ClipVertex(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2ClipVertex obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ClipVertex() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ClipVertex(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Vec2 v {
    set {
      Box2DPINVOKE.b2ClipVertex_v_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ClipVertex_v_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2ContactID id {
    set {
      Box2DPINVOKE.b2ClipVertex_id_set(swigCPtr, b2ContactID.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ClipVertex_id_get(swigCPtr);
      b2ContactID ret = (cPtr == IntPtr.Zero) ? null : new b2ContactID(cPtr, false);
      return ret;
    } 
  }

  public b2ClipVertex() : this(Box2DPINVOKE.new_b2ClipVertex(), true) {
  }

}

}
