/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2ContactListener : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ContactListener(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2ContactListener obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ContactListener() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ContactListener(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void BeginContact(b2Contact contact) {
    Box2DPINVOKE.b2ContactListener_BeginContact(swigCPtr, b2Contact.getCPtr(contact));
  }

  public virtual void EndContact(b2Contact contact) {
    Box2DPINVOKE.b2ContactListener_EndContact(swigCPtr, b2Contact.getCPtr(contact));
  }

  public virtual void PreSolve(b2Contact contact, b2Manifold oldManifold) {
    Box2DPINVOKE.b2ContactListener_PreSolve(swigCPtr, b2Contact.getCPtr(contact), b2Manifold.getCPtr(oldManifold));
  }

  public virtual void PostSolve(b2Contact contact, b2ContactImpulse impulse) {
    Box2DPINVOKE.b2ContactListener_PostSolve(swigCPtr, b2Contact.getCPtr(contact), b2ContactImpulse.getCPtr(impulse));
  }

  public b2ContactListener() : this(Box2DPINVOKE.new_b2ContactListener(), true) {
  }

}

}
