/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2ContactFeature : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ContactFeature(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2ContactFeature obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ContactFeature() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ContactFeature(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public byte indexA {
    set {
      Box2DPINVOKE.b2ContactFeature_indexA_set(swigCPtr, value);
    } 
    get {
      byte ret = Box2DPINVOKE.b2ContactFeature_indexA_get(swigCPtr);
      return ret;
    } 
  }

  public byte indexB {
    set {
      Box2DPINVOKE.b2ContactFeature_indexB_set(swigCPtr, value);
    } 
    get {
      byte ret = Box2DPINVOKE.b2ContactFeature_indexB_get(swigCPtr);
      return ret;
    } 
  }

  public byte typeA {
    set {
      Box2DPINVOKE.b2ContactFeature_typeA_set(swigCPtr, value);
    } 
    get {
      byte ret = Box2DPINVOKE.b2ContactFeature_typeA_get(swigCPtr);
      return ret;
    } 
  }

  public byte typeB {
    set {
      Box2DPINVOKE.b2ContactFeature_typeB_set(swigCPtr, value);
    } 
    get {
      byte ret = Box2DPINVOKE.b2ContactFeature_typeB_get(swigCPtr);
      return ret;
    } 
  }

  public b2ContactFeature() : this(Box2DPINVOKE.new_b2ContactFeature(), true) {
  }

  public enum Type {
    e_vertex = 0,
    e_face = 1
  }

}

}
