/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2ContactImpulse : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ContactImpulse(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2ContactImpulse obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ContactImpulse() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ContactImpulse(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_float normalImpulses {
    set {
      Box2DPINVOKE.b2ContactImpulse_normalImpulses_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ContactImpulse_normalImpulses_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_float tangentImpulses {
    set {
      Box2DPINVOKE.b2ContactImpulse_tangentImpulses_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ContactImpulse_tangentImpulses_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public int count {
    set {
      Box2DPINVOKE.b2ContactImpulse_count_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2ContactImpulse_count_get(swigCPtr);
      return ret;
    } 
  }

  public b2ContactImpulse() : this(Box2DPINVOKE.new_b2ContactImpulse(), true) {
  }

}

}
