/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2DistanceInput : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2DistanceInput(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2DistanceInput obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2DistanceInput() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2DistanceInput(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2DistanceProxy proxyA {
    set {
      Box2DPINVOKE.b2DistanceInput_proxyA_set(swigCPtr, b2DistanceProxy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2DistanceInput_proxyA_get(swigCPtr);
      b2DistanceProxy ret = (cPtr == IntPtr.Zero) ? null : new b2DistanceProxy(cPtr, false);
      return ret;
    } 
  }

  public b2DistanceProxy proxyB {
    set {
      Box2DPINVOKE.b2DistanceInput_proxyB_set(swigCPtr, b2DistanceProxy.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2DistanceInput_proxyB_get(swigCPtr);
      b2DistanceProxy ret = (cPtr == IntPtr.Zero) ? null : new b2DistanceProxy(cPtr, false);
      return ret;
    } 
  }

  public b2Transform transformA {
    set {
      Box2DPINVOKE.b2DistanceInput_transformA_set(swigCPtr, b2Transform.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2DistanceInput_transformA_get(swigCPtr);
      b2Transform ret = (cPtr == IntPtr.Zero) ? null : new b2Transform(cPtr, false);
      return ret;
    } 
  }

  public b2Transform transformB {
    set {
      Box2DPINVOKE.b2DistanceInput_transformB_set(swigCPtr, b2Transform.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2DistanceInput_transformB_get(swigCPtr);
      b2Transform ret = (cPtr == IntPtr.Zero) ? null : new b2Transform(cPtr, false);
      return ret;
    } 
  }

  public bool useRadii {
    set {
      Box2DPINVOKE.b2DistanceInput_useRadii_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2DistanceInput_useRadii_get(swigCPtr);
      return ret;
    } 
  }

  public b2DistanceInput() : this(Box2DPINVOKE.new_b2DistanceInput(), true) {
  }

}

}
