/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2FixtureDef : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2FixtureDef(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2FixtureDef obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2FixtureDef() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2FixtureDef(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2FixtureDef() : this(Box2DPINVOKE.new_b2FixtureDef(), true) {
  }

  public b2Shape shape {
    set {
      Box2DPINVOKE.b2FixtureDef_shape_set(swigCPtr, b2Shape.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2FixtureDef_shape_get(swigCPtr);
      b2Shape ret = (cPtr == IntPtr.Zero) ? null : new b2Shape(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_void userData {
    set {
      Box2DPINVOKE.b2FixtureDef_userData_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2FixtureDef_userData_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public float friction {
    set {
      Box2DPINVOKE.b2FixtureDef_friction_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2FixtureDef_friction_get(swigCPtr);
      return ret;
    } 
  }

  public float restitution {
    set {
      Box2DPINVOKE.b2FixtureDef_restitution_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2FixtureDef_restitution_get(swigCPtr);
      return ret;
    } 
  }

  public float density {
    set {
      Box2DPINVOKE.b2FixtureDef_density_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2FixtureDef_density_get(swigCPtr);
      return ret;
    } 
  }

  public bool isSensor {
    set {
      Box2DPINVOKE.b2FixtureDef_isSensor_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2FixtureDef_isSensor_get(swigCPtr);
      return ret;
    } 
  }

  public b2Filter filter {
    set {
      Box2DPINVOKE.b2FixtureDef_filter_set(swigCPtr, b2Filter.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2FixtureDef_filter_get(swigCPtr);
      b2Filter ret = (cPtr == IntPtr.Zero) ? null : new b2Filter(cPtr, false);
      return ret;
    } 
  }

}

}
