/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2FixtureProxy : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2FixtureProxy(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2FixtureProxy obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2FixtureProxy() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2FixtureProxy(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2AABB aabb {
    set {
      Box2DPINVOKE.b2FixtureProxy_aabb_set(swigCPtr, b2AABB.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2FixtureProxy_aabb_get(swigCPtr);
      b2AABB ret = (cPtr == IntPtr.Zero) ? null : new b2AABB(cPtr, false);
      return ret;
    } 
  }

  public b2Fixture fixture {
    set {
      Box2DPINVOKE.b2FixtureProxy_fixture_set(swigCPtr, b2Fixture.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2FixtureProxy_fixture_get(swigCPtr);
      b2Fixture ret = (cPtr == IntPtr.Zero) ? null : new b2Fixture(cPtr, false);
      return ret;
    } 
  }

  public int childIndex {
    set {
      Box2DPINVOKE.b2FixtureProxy_childIndex_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2FixtureProxy_childIndex_get(swigCPtr);
      return ret;
    } 
  }

  public int proxyId {
    set {
      Box2DPINVOKE.b2FixtureProxy_proxyId_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2FixtureProxy_proxyId_get(swigCPtr);
      return ret;
    } 
  }

  public b2FixtureProxy() : this(Box2DPINVOKE.new_b2FixtureProxy(), true) {
  }

}

}
