/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2JointEdge : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2JointEdge(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2JointEdge obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2JointEdge() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2JointEdge(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Body other {
    set {
      Box2DPINVOKE.b2JointEdge_other_set(swigCPtr, b2Body.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2JointEdge_other_get(swigCPtr);
      b2Body ret = (cPtr == IntPtr.Zero) ? null : new b2Body(cPtr, false);
      return ret;
    } 
  }

  public b2Joint joint {
    set {
      Box2DPINVOKE.b2JointEdge_joint_set(swigCPtr, b2Joint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2JointEdge_joint_get(swigCPtr);
      b2Joint ret = (cPtr == IntPtr.Zero) ? null : new b2Joint(cPtr, false);
      return ret;
    } 
  }

  public b2JointEdge prev {
    set {
      Box2DPINVOKE.b2JointEdge_prev_set(swigCPtr, b2JointEdge.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2JointEdge_prev_get(swigCPtr);
      b2JointEdge ret = (cPtr == IntPtr.Zero) ? null : new b2JointEdge(cPtr, false);
      return ret;
    } 
  }

  public b2JointEdge next {
    set {
      Box2DPINVOKE.b2JointEdge_next_set(swigCPtr, b2JointEdge.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2JointEdge_next_get(swigCPtr);
      b2JointEdge ret = (cPtr == IntPtr.Zero) ? null : new b2JointEdge(cPtr, false);
      return ret;
    } 
  }

  public b2JointEdge() : this(Box2DPINVOKE.new_b2JointEdge(), true) {
  }

}

}
