/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2ManifoldPoint : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ManifoldPoint(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2ManifoldPoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ManifoldPoint() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ManifoldPoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Vec2 localPoint {
    set {
      Box2DPINVOKE.b2ManifoldPoint_localPoint_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ManifoldPoint_localPoint_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public float normalImpulse {
    set {
      Box2DPINVOKE.b2ManifoldPoint_normalImpulse_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2ManifoldPoint_normalImpulse_get(swigCPtr);
      return ret;
    } 
  }

  public float tangentImpulse {
    set {
      Box2DPINVOKE.b2ManifoldPoint_tangentImpulse_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2ManifoldPoint_tangentImpulse_get(swigCPtr);
      return ret;
    } 
  }

  public b2ContactID id {
    set {
      Box2DPINVOKE.b2ManifoldPoint_id_set(swigCPtr, b2ContactID.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2ManifoldPoint_id_get(swigCPtr);
      b2ContactID ret = (cPtr == IntPtr.Zero) ? null : new b2ContactID(cPtr, false);
      return ret;
    } 
  }

  public b2ManifoldPoint() : this(Box2DPINVOKE.new_b2ManifoldPoint(), true) {
  }

}

}
