/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2PulleyJointDef : b2JointDef {
  private HandleRef swigCPtr;

  internal b2PulleyJointDef(IntPtr cPtr, bool cMemoryOwn) : base(Box2DPINVOKE.b2PulleyJointDef_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2PulleyJointDef obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2PulleyJointDef() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2PulleyJointDef(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public b2PulleyJointDef() : this(Box2DPINVOKE.new_b2PulleyJointDef(), true) {
  }

  public void Initialize(b2Body bodyA, b2Body bodyB, b2Vec2 groundAnchorA, b2Vec2 groundAnchorB, b2Vec2 anchorA, b2Vec2 anchorB, float ratio) {
    Box2DPINVOKE.b2PulleyJointDef_Initialize(swigCPtr, b2Body.getCPtr(bodyA), b2Body.getCPtr(bodyB), b2Vec2.getCPtr(groundAnchorA), b2Vec2.getCPtr(groundAnchorB), b2Vec2.getCPtr(anchorA), b2Vec2.getCPtr(anchorB), ratio);
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public b2Vec2 groundAnchorA {
    set {
      Box2DPINVOKE.b2PulleyJointDef_groundAnchorA_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2PulleyJointDef_groundAnchorA_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 groundAnchorB {
    set {
      Box2DPINVOKE.b2PulleyJointDef_groundAnchorB_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2PulleyJointDef_groundAnchorB_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localAnchorA {
    set {
      Box2DPINVOKE.b2PulleyJointDef_localAnchorA_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2PulleyJointDef_localAnchorA_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localAnchorB {
    set {
      Box2DPINVOKE.b2PulleyJointDef_localAnchorB_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2PulleyJointDef_localAnchorB_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public float lengthA {
    set {
      Box2DPINVOKE.b2PulleyJointDef_lengthA_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PulleyJointDef_lengthA_get(swigCPtr);
      return ret;
    } 
  }

  public float lengthB {
    set {
      Box2DPINVOKE.b2PulleyJointDef_lengthB_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PulleyJointDef_lengthB_get(swigCPtr);
      return ret;
    } 
  }

  public float ratio {
    set {
      Box2DPINVOKE.b2PulleyJointDef_ratio_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2PulleyJointDef_ratio_get(swigCPtr);
      return ret;
    } 
  }

}

}
