/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2RayCastOutput : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2RayCastOutput(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2RayCastOutput obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2RayCastOutput() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2RayCastOutput(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Vec2 normal {
    set {
      Box2DPINVOKE.b2RayCastOutput_normal_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2RayCastOutput_normal_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public float fraction {
    set {
      Box2DPINVOKE.b2RayCastOutput_fraction_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2RayCastOutput_fraction_get(swigCPtr);
      return ret;
    } 
  }

  public b2RayCastOutput() : this(Box2DPINVOKE.new_b2RayCastOutput(), true) {
  }

}

}
