/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2SolverData : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2SolverData(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2SolverData obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2SolverData() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2SolverData(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2TimeStep step {
    set {
      Box2DPINVOKE.b2SolverData_step_set(swigCPtr, b2TimeStep.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2SolverData_step_get(swigCPtr);
      b2TimeStep ret = (cPtr == IntPtr.Zero) ? null : new b2TimeStep(cPtr, false);
      return ret;
    } 
  }

  public b2Position positions {
    set {
      Box2DPINVOKE.b2SolverData_positions_set(swigCPtr, b2Position.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2SolverData_positions_get(swigCPtr);
      b2Position ret = (cPtr == IntPtr.Zero) ? null : new b2Position(cPtr, false);
      return ret;
    } 
  }

  public b2Velocity velocities {
    set {
      Box2DPINVOKE.b2SolverData_velocities_set(swigCPtr, b2Velocity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2SolverData_velocities_get(swigCPtr);
      b2Velocity ret = (cPtr == IntPtr.Zero) ? null : new b2Velocity(cPtr, false);
      return ret;
    } 
  }

  public b2SolverData() : this(Box2DPINVOKE.new_b2SolverData(), true) {
  }

}

}
