/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2TreeNode : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2TreeNode(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2TreeNode obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2TreeNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2TreeNode(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public bool IsLeaf() {
    bool ret = Box2DPINVOKE.b2TreeNode_IsLeaf(swigCPtr);
    return ret;
  }

  public b2AABB aabb {
    set {
      Box2DPINVOKE.b2TreeNode_aabb_set(swigCPtr, b2AABB.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2TreeNode_aabb_get(swigCPtr);
      b2AABB ret = (cPtr == IntPtr.Zero) ? null : new b2AABB(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_void userData {
    set {
      Box2DPINVOKE.b2TreeNode_userData_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2TreeNode_userData_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public int child1 {
    set {
      Box2DPINVOKE.b2TreeNode_child1_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2TreeNode_child1_get(swigCPtr);
      return ret;
    } 
  }

  public int child2 {
    set {
      Box2DPINVOKE.b2TreeNode_child2_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2TreeNode_child2_get(swigCPtr);
      return ret;
    } 
  }

  public int height {
    set {
      Box2DPINVOKE.b2TreeNode_height_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2TreeNode_height_get(swigCPtr);
      return ret;
    } 
  }

  public b2TreeNode() : this(Box2DPINVOKE.new_b2TreeNode(), true) {
  }

}

}
