/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2Transform : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Transform(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2Transform obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Transform() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Transform(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public b2Transform() : this(Box2DPINVOKE.new_b2Transform__SWIG_0(), true) {
  }

  public b2Transform(b2Vec2 position, b2Rot rotation) : this(Box2DPINVOKE.new_b2Transform__SWIG_1(b2Vec2.getCPtr(position), b2Rot.getCPtr(rotation)), true) {
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetIdentity() {
    Box2DPINVOKE.b2Transform_SetIdentity(swigCPtr);
  }

  public void Set(b2Vec2 position, float angle) {
    Box2DPINVOKE.b2Transform_Set(swigCPtr, b2Vec2.getCPtr(position), angle);
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public b2Vec2 p {
    set {
      Box2DPINVOKE.b2Transform_p_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2Transform_p_get(swigCPtr);
      b2Vec2 ret = (cPtr == IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Rot q {
    set {
      Box2DPINVOKE.b2Transform_q_set(swigCPtr, b2Rot.getCPtr(value));
    } 
    get {
      IntPtr cPtr = Box2DPINVOKE.b2Transform_q_get(swigCPtr);
      b2Rot ret = (cPtr == IntPtr.Zero) ? null : new b2Rot(cPtr, false);
      return ret;
    } 
  }

}

}
