/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Box2DCS {

using System;
using System.Runtime.InteropServices;

public class b2WeldJoint : b2Joint {
  private HandleRef swigCPtr;

  internal b2WeldJoint(IntPtr cPtr, bool cMemoryOwn) : base(Box2DPINVOKE.b2WeldJoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(b2WeldJoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2WeldJoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2WeldJoint(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public override b2Vec2 GetAnchorA() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2WeldJoint_GetAnchorA(swigCPtr), true);
    return ret;
  }

  public override b2Vec2 GetAnchorB() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2WeldJoint_GetAnchorB(swigCPtr), true);
    return ret;
  }

  public override b2Vec2 GetReactionForce(float inv_dt) {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2WeldJoint_GetReactionForce(swigCPtr, inv_dt), true);
    return ret;
  }

  public override float GetReactionTorque(float inv_dt) {
    float ret = Box2DPINVOKE.b2WeldJoint_GetReactionTorque(swigCPtr, inv_dt);
    return ret;
  }

  public b2Vec2 GetLocalAnchorA() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2WeldJoint_GetLocalAnchorA(swigCPtr), false);
    return ret;
  }

  public b2Vec2 GetLocalAnchorB() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2WeldJoint_GetLocalAnchorB(swigCPtr), false);
    return ret;
  }

  public float GetReferenceAngle() {
    float ret = Box2DPINVOKE.b2WeldJoint_GetReferenceAngle(swigCPtr);
    return ret;
  }

  public void SetFrequency(float hz) {
    Box2DPINVOKE.b2WeldJoint_SetFrequency(swigCPtr, hz);
  }

  public float GetFrequency() {
    float ret = Box2DPINVOKE.b2WeldJoint_GetFrequency(swigCPtr);
    return ret;
  }

  public void SetDampingRatio(float ratio) {
    Box2DPINVOKE.b2WeldJoint_SetDampingRatio(swigCPtr, ratio);
  }

  public float GetDampingRatio() {
    float ret = Box2DPINVOKE.b2WeldJoint_GetDampingRatio(swigCPtr);
    return ret;
  }

  public override void Dump() {
    Box2DPINVOKE.b2WeldJoint_Dump(swigCPtr);
  }

}

}
